spring:
  application:
    name: Immobiliare
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/immobiliare?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000      # 10 minuti
      connection-timeout: 30000 # 30 secondi
      max-lifetime: 1800000     # 30 minuti
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

jwt:
  secret: ${JWT_SECRET:Example}
